### ISSUE TITLE
Can not download the repository token

### ISSUE THREAD

**Issue by marco-buttu** [discos/deployment#390]
The _Download the repository token_ rule listed in [dependencies/tasks/main.yml](https://github.com/discos/deployment/blob/master/ansible/roles/dependencies/tasks/main.yml)
 executes the command:

`git clone git@github.com:discos/dependencies.git`

It fails because that is a private repository. If you agree, I add a note in the documentation about adding a SSH public key to Github.

**Comment by giuseppe-carboni** [comment]
The doc has already been updated in this very repository. [This is the file with the update.](https://github.com/discos/deployment/blob/master/doc/quickstart.rst)
Unfortunately, as we already talked about, this update should be ported to the discos/doc repository too in order to show up in the readthedocs page.

**Comment by marco-buttu** [comment]
I was reading the ReadTheDocs documentation and I did not realize that the README file of deployments repo is pointing to the discos documentation. Got it.
